version: '3'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
      NODE_ENV : docker
    volumes:
     - ../services/mobileService:/usr/src/app
    depends_on:
    - database
